spring.application.name=Human-Core API

server.error.include-message=always
server.error.include-binding-errors=always

# Configura??o da conex?o com o banco (usada internamente pelo JPA)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Configura??es do JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.open-in-view=false

broker.exchange.name=emailsender.direct.exchange
broker.queue.name=emailsender.queue
broker.queue.reset-senha=email.reset-senha

logging.level.org.springframework.amqp=DEBUG
logging.level.org.springframework.amqp.rabbit.core.RabbitAdmin=DEBUG

spring.jpa.defer-datasource-initialization=true
# tempo de expira??o do token em milissegundos (esse valor indica que ele vai expirar em 1 hora)
jwt.validity=3600000
# palavra passe do token (segredo) necessita de no minimo 32 caracteres e serve para assinar e verificar os tokens, sendo recomend?vel usar uma chave complexa e dif?cil de advinhar para aumentar a seguran?a da aplica??o
jwt.secret=RXhpc3RlIHVtYSB0ZW9yaWEgcXVlIGRpeiBxdWUsIHNlIHVtIGRpYSBhbGd16W0gZGVzY29icmlyIGV4YXRhbWVudGUgcGFyYSBxdWUgc2VydmUgbyBVbml2ZXJzbyBlIHBvciBxdWUgc2VsaWUgZXN0wSBhcXVpLCBlbGUgZGVzYXBhcmVjZXJhIGluc3RhbnRhbmVhbWVudGUgc2Vy4SBzdWJzdGl0dWXlZG8gcG9yIGFsZ28gYWluZGEgbWFpcyBlc3RyYW5obyBlIGluZXhwbGlwYXZlbC4gRXhpc3RlIHVtYSBzZWd1bmRhIHRlb3JpYSBxdWUgZGl6IHF1ZSBpc3NvIGjhIGFjb250ZWNldS4uLg==

server.port=8080

spring.main.allow-circular-references=true

# PROD
# spring.datasource.url=jdbc:mysql://10.0.0.108:3306/humandb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
# spring.datasource.username=myapp
# spring.datasource.password=jP19042014#

# spring.rabbitmq.host=10.0.0.82
# spring.rabbitmq.port=5672
# spring.rabbitmq.username=myuser
# spring.rabbitmq.password=MyRabbitPass
# spring.rabbitmq.virtual-host=myvhost

# DEV
spring.datasource.url=jdbc:mysql://localhost:3306/newTesteHuman?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=16012004

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=myuser
spring.rabbitmq.password=secret

websocket.service.url=http://localhost:8082/notification

jwt.reset.validity=900000
websocket.service.url=http://localhost:8082/notification# Tipo de cache
spring.cache.type=redis

# Config do Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# (Opcional) Time-to-live padrão para o cache
spring.cache.redis.time-to-live=600000
