on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build da imagem
        run: docker build -t meuuser/meuapp:latest .

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Push da imagem
        run: docker push meuuser/meuapp:latest

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull humanuser/humanapp:latest
            docker stop humanapp || true
            docker rm humanapp || true
            docker run -d --name humanapp -p 8080:8080 humanuser/humanapp:latest